
# MANDATORY SITE SETTINGS
# =======================

url: https://mrbin.fr
baseurl: ""
title: Mr Bin
email: bonjour@mrbin.fr
description: "Votre coach zéro-déchet"

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from


# JEKYLL PLUGINS
# ==============

# Jekyll SEO plugin
lang: fr_FR
twitter:
    username: Mrbin_Fr
logo: /img/logos/logo.png
image: 
    path: /img/logos/logo.png

# JEKYLL TEMPLATE
# ===============

# Team names, titles and social links
people:
  - name: Cécile
    pic: cecile-tostivint
    position: Mrs Bin
    desc: |
      Il y a un peu plus d'un an, Cécile est devenue zéro-déchet.
      Un jour elle parle à Glenn de
      son envie d’aider chaque citoyen à
      réduire ses déchets. Mais elle n’a
      pas le don d’ubiquité, il faut trouver une 
      solution pour aider un maximum de monde !
    social:
  - name: Glenn
    pic: glenn-rolland
    position: Mr Bin
    desc: |
      Glenn, entrepreneur spécialisé
      dans la production d'outils numériques,
      parle à Cécile des chatbots,
      ces nouveaux conseillers virtuels
      qui ont la possibilité d’aider tous
      ceux qui le souhaitent à réduire
      leurs déchets. L’aventure peut
      commencer !
    social:
    
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://m.me/mrbin-fr
    username: "/mrbin-fr"
#  - title: twitter
#  url: https://twitter.com/MrBin_Fr
#  username: "@MrBin_Fr"

# Postal address (add as many lines as necessary)
address:
  - line: Paris

# Build settings
markdown: kramdown
permalink: pretty
permalink: contact

