
# MANDATORY SITE SETTINGS
# =======================

url: https://mrbin.fr
baseurl: ""
title: Mr Bin
email: bonjour@mrbin.fr
description: "Votre coach zéro-déchet"

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from


# JEKYLL PLUGINS
# ==============

# Jekyll SEO plugin
lang: fr_FR
twitter:
    username: Mrbin_Fr
logo: /img/logos/logo-color-blackbg.256p.png
image: 
    path: /img/logos/logo-color-blackbg.256p.png

# JEKYLL TEMPLATE
# ===============

# Team names, titles and social links
people:
  - name: Cécile<br/>TOSTIVINT
    pic: cecile-tostivint
    position: Présidente
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/c%C3%A9cile-tostivint-12888a80
      - title: twitter
        url: https://twitter.com/ceciletostivint

  - name: Glenn<br/>ROLLAND
    pic: glenn-rolland
    position: Directeur technique 
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/glenux/
      - title: twitter
        url: https://twitter.com/glenux


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MrBin_Fr
    username: "@MrBin_Fr"
  - title: facebook
    url: https://m.me/mrbin-fr
    username: "/mrbin-fr"

# Postal address (add as many lines as necessary)
address:
  - line: Paris

# Build settings
markdown: kramdown
permalink: pretty
permalink: contact

