
# MANDATORY SITE SETTINGS
# =======================

url: https://mrbin.fr
baseurl: ""
title: Mr Bin
email: bonjour@mrbin.fr
description: "Votre coach zéro-déchet"

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from


# JEKYLL PLUGINS
# ==============

# Jekyll SEO plugin
lang: fr_FR
twitter:
    username: Mrbin_Fr
logo: /img/logos/logo.png
image: 
    path: /img/logos/logo.png

# JEKYLL TEMPLATE
# ===============

# Team names, titles and social links
    
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/mrbin.fr/
    username: "/mrbin-fr"
#   url: https://m.me/mrbin-fr

#  - title: twitter
#  url: https://twitter.com/MrBin_Fr
#  username: "@MrBin_Fr"

# Postal address (add as many lines as necessary)
address:
  - line: Paris

# Build settings
markdown: kramdown
permalink: pretty
permalink: contact

